_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "TINYIMAGENET"
  DATAPATH: "NotNeeded"  #TODO: need to specify here
  NUMBER_CLASSES: 322
  MULTILABEL: False
  BATCH_SIZE: 64
  FEATURE: "sup_vitb16_imagenet21k"
MODEL:
  TRANSFER_TYPE: "prompt"
  TYPE: "vit"
  SAVE_CKPT: True
  PROMPT:
    NUM_TOKENS: 10
    DEEP: True
    DROPOUT: 0.1
    SAVE_FOR_EACH_EPOCH: True
  MODEL_ROOT: "D_ALL/models"
SOLVER:
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.01
  TOTAL_EPOCH: 40
  STRATEGY: "bvs"
  INIT_POOL: 400
  SEL_AL: 400
  NUM_AL: 5
  INIT_FILE_NAME: "tiny_img_cls_init.csv"
  KL_VAL: 1.0
  LOO: 0